### ISSUE TITLE
[Question] - Is it possible to run this demo locally

### ISSUE THREAD

**Issue by vnl** [avinashkumar1289/bank-of-anthos#1]
Hi, 

I am trying to strip out all reliance on running this demo on GCP. 
Possibly try to run it on different clouds (AWS and or Azure). 
Is this even possible?

**Comment by avinashkumar1289** [comment]
Hi,

Yeah it should be possible to deploy this on any Kubernetes Platform. Are you facing any issues ?

**Comment by vnl** [comment]
Sorry about the late reply but yeah, loads of issues. I am not sure I am doing anything right at this point. I can share the error messages.

**Comment by avinashkumar1289** [comment]
Sorry for the late response.Kindly share the error..I can have a look .Thanks

**Comment by vnl** [comment]
Not at all, I appreciate your offering to help. 

I think the issue I face is that it looks at GOOGLE_APPLICATION_CREDENTIALS. I need to strip everything that is looking for a ProjectID from GCP.

```
skaffold run > skaffoldoutput.txt
I0725 19:01:47.818982   85903 request.go:668] Waited for 1.132283986s due to client-side throttling, not priority and fairness, request: GET:https://kubernetes.docker.internal:6443/api/v1/namespaces/default/pods?labelSelector=app%!D(MISSING)balancereader%!C(MISSING)skaffold.dev%!F(MISSING)run-id%!D(MISSING)32149071-7451-4bf4-9386-c11e29e410f1
1/9 deployment(s) failed
```
Pasted the output in pastebin: https://pastebin.com/fkCgnARN

![image](https://user-images.githubusercontent.com/1355466/180842806-f864a834-6e04-4ca8-a035-dc6142c02c86.png)

Hopefully, this gives an idea of what is happening.

**Comment by avinashkumar1289** [comment]
@vnl I tried deploying the manifest files to GKE environment. I was able to do that without any issues.
I used the following command

```
kubectl apply -f ./extras/jwt/jwt-secret.yaml
kubectl apply -f ./kubernetes-manifests
```
Can you check if this works ? 
Otherwise can you share the logs for the crashloopbackoff pods ? 
Thanks !!

**Comment by vnl** [comment]
@avinashkumar1289 I am sorry if this is a silly question. I would want to deploy it locally say docker desktop. I do not want to deploy it to GKE. Is that even possible?

**Comment by avinashkumar1289** [comment]
@vnl docker-desktop includes a standalone k8s server and that can also be used to deploy these manifest files.. 
I don't think these k8s manifets have any dependencies on GCP. So if you try to check the logs of the failed pods you might get more info..

**Comment by vnl** [comment]
@avinashkumar1289 ah, thank you. I did that now. 
Found these, in all the crashing pods:
The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

Full log: https://pastebin.com/c2YfjYnR

**Comment by avinashkumar1289** [comment]
Okay Got it. Looks like pushed in a flag.Can you  update these flags in the deployment files where they are used..and you should be good..I will update the manifest files as well 
     ```
     - name: ENABLE_TRACING
          value: "false"
        - name: ENABLE_METRICS
          value: "false"
      ```

**Comment by avinashkumar1289** [comment]
@vnl Pushed in the new changes..Please check.Thanks !! This should work

**Comment by vnl** [comment]
Thanks for this @avinashkumar1289 however, there are a couple of pods (userservice and contacts) still crashing. 

![image](https://user-images.githubusercontent.com/1355466/181056433-5d5bef83-dfba-4ddf-b77a-4929bdcda15d.png)


Funnily enough, it is the same error: 
```
{"timestamp": "2022-07-26 15:49:41", "message": "info | Starting gunicorn 20.1.0", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:41", "message": "info | Listening at: http://0.0.0.0:8080 (7)", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:41", "message": "info | Using worker: gthread", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:41", "message": "info | Booting worker with pid: 8", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:44", "message": "create_app | Starting contacts service.", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:44", "message": "create_app | ✅ Tracing enabled.", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:44", "message": "ping | Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused", "severity": "WARNING"}
{"timestamp": "2022-07-26 15:49:44", "message": "ping | Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused", "severity": "WARNING"}
{"timestamp": "2022-07-26 15:49:44", "message": "ping | Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused", "severity": "WARNING"}
{"timestamp": "2022-07-26 15:49:44", "message": "_get_gce_credentials | Authentication failed using Compute Engine authentication due to unavailable metadata server.", "severity": "WARNING"}
{"timestamp": "2022-07-26 15:49:44", "message": "exception | Exception in worker process", "severity": "ERROR"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/app/contacts.py", line 203, in create_app
    cloud_trace_exporter = CloudTraceSpanExporter()
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/exporter/cloud_trace/__init__.py", line 144, in __init__
    self.client: TraceServiceClient = client or TraceServiceClient()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/trace_v2/services/trace_service/client.py", line 425, in __init__
    self._transport = Transport(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/trace_v2/services/trace_service/transports/grpc.py", line 155, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/trace_v2/services/trace_service/transports/base.py", line 111, in __init__
    credentials, _ = google.auth.default(
  File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 616, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
{"timestamp": "2022-07-26 15:49:44", "message": "info | Worker exiting (pid: 8)", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:44", "message": "_shutdown | Stopping contacts service.", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:45", "message": "info | Shutting down: Master", "severity": "INFO"}
{"timestamp": "2022-07-26 15:49:45", "message": "info | Reason: Worker failed to boot.", "severity": "INFO"}
```

**Comment by avinashkumar1289** [comment]
@vnl Are you sure tracing is disabled in the deployment.yaml files for contact and user service..
From the logs its looks like its still enabled
```
{"timestamp": "2022-07-26 15:49:44", "message": "create_app | ✅ Tracing enabled.", "severity": "INFO"}
```

**Comment by vnl** [comment]
@avinashkumar1289 you were right, I had missed a few files. 
I have them all up but I get all sorts of different errors now. 
![image](https://user-images.githubusercontent.com/1355466/181217452-fdf9de18-6c16-4089-bb5e-41efcb33c201.png)

https://pastebin.com/cdNQsmtc

A couple of them crash and restart. org.postgresql.util.PSQLException: The connection attempt failed. 
I do not need any other pre-req right?

![image](https://user-images.githubusercontent.com/1355466/181221165-f2bf0fe5-ea2d-4f6e-8a76-bb840a59ea0b.png)

BalanceReade, LedgerWriter & transactionhistory crash and then restart. 

Really sorry, I am asking so many questions. I want to get to the bottom of this and get this working locally.

**Comment by vnl** [comment]
Please ignore the previous comment. 
As you can see everything seems to be running. 
![image](https://user-images.githubusercontent.com/1355466/181225786-edf261ff-8983-4e09-b83a-cbcb7b6465c9.png)

The fix was to disable my VPN. 

If I may further this conversation, the load generator is doing its magic and I am sure things are fine there. 
Is there a way to actually interact with the front end? 
I assumed it's as easy as getting the IP and port, but...
![image](https://user-images.githubusercontent.com/1355466/181226610-d06e24c1-a4bc-443b-8039-234f4cb8dd54.png)

**Comment by vnl** [comment]
Thank you for the help, it finally got working.
